Add reset password function
DeanHoang/.NET_Team_DemoProject pull request #13
Opened 2021-08-30 10:01 UTC by Nguyen-Ba-Cong

Please check my code and give me review.
Thank you very much

2021-08-30 10:19 UTC, vancuong196 requested changes

2021-08-30 10:19 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP/appsettings.json
> +    "AppCnn": "Data Source=DESKTOP-1JO6K8V\\SQLEXPRESS; Initial Catalog= souvenir_store ; Integrated Security=True;"
You can use .\\\SQLEXPRESS or change it locally and don't commit this file.

2021-08-30 10:19 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP/Controllers/AccountController.cs
> +                Random rand = new Random();
put this business code inside a service

2021-08-30 10:19 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Repository/Implement/AccountRepository.cs
> +                account.Password = password;
Did you encrypt  the password?

2021-08-30 10:19 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Service/Implement/AccountService.cs
> +                if (changePasswordModel.OldPassword != oldPassword)
please compare 2 encrypted password

2021-08-30 10:19 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Repository/Implement/AccountRepository.cs
> +                    accountChange.Password = password;
encrypt the password, check for Jessie code

2021-08-30 10:32 UTC, Nguyen-Ba-Cong commented on DEMO-PROJECT-BE/DP/appsettings.json
> +    "AppCnn": "Data Source=DESKTOP-1JO6K8V\\SQLEXPRESS; Initial Catalog= souvenir_store ; Integrated Security=True;"
I added the Sendgrid key in this file.  Do I need to commit this file?

2021-08-30 10:42 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP/appsettings.json
> +    "AppCnn": "Data Source=DESKTOP-1JO6K8V\\SQLEXPRESS; Initial Catalog= souvenir_store ; Integrated Security=True;"
Yes but remove your device credentials using .\\SQLEXPRESS

2021-08-31 04:03 UTC, vancuong196 requested changes

2021-08-31 04:03 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Repository/Implement/RoleRepository.cs
> +                    if (role.Name != null)
Use String.IsNullOrEmpty to check null or empty. 
You can use "Admin".equals(role) to remove this additional null check.
Make role ADMIN as a const string.

2021-08-31 04:03 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Infrastructure/obj/project.nuget.cache
> +{
Ingore

2021-08-31 04:03 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Infrastructure/obj/project.assets.json
> +{
Ignore

2021-08-31 07:55 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Repository/Implement/RoleRepository.cs
> +                    if (role.Name.Equals(ADMIN))
ADMIN.equals()

2021-08-31 10:14 UTC, closed without merging