Sprint 01- JWT auth and password encoding.
DeanHoang/.NET_Team_DemoProject pull request #4
Opened 2021-08-25 09:43 UTC by Trinhnguyen1704

JWT token and password encoding.

2021-08-25 10:14 UTC, vancuong196 requested changes

2021-08-25 10:14 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Service/Implement/Auth/PasswordService.cs
> +        public string PasswordEncoder(string password)
This will not protect the password because anyone can convert a base64 string back to a password string.
This is example how to encrypt your password:
https://www.automationmission.com/2020/09/17/hashing-and-salting-passwords-in-c/

2021-08-25 10:14 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Service/Implement/Auth/PasswordService.cs
> +                encodeDataByte = System.Text.Encoding.UTF8.GetBytes(password);
don't need to initialize encodeDataByte before calling GetBytes(), just: var encodeDataByte = System.Text.Encoding.UTF8.GetBytes(password);

2021-08-25 10:14 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP/appsettings.json
> +  "JwtKey" : "Souvenir Store Application Key"
Use a complex random key

2021-08-28 01:18 UTC, Trinhnguyen1704 commented
Hi, Cuong!
I researched and tested the hash and salt, I follow this way when we login:

Firstly, check whether the user name exists. If it exists, get the user's
salt.

Secondly, use the salt and the password which was entered by the user to
compute the hash value as passwordandsalt field.

Finally, compare the passwordandsalt with the hash value in the database.

So we need to add a salt field in Account entity.

Could you give me reviews for this solution ?

Thank you so much!
-----------------------------------------------
My best regards,

Nguyen Thi Thuy Trinh
Da Nang University of Science and Technology
Phone:  +84 339 936 145
Address:  08, Ha Van Tinh, Lien Chieu, Da Nang


On Fri, Aug 27, 2021 at 10:58 PM Cuong ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In DEMO-PROJECT-BE/DP.Service/Implement/Auth/PasswordService.cs
> <https://github.com/DeanHoang/.NET_Team_DemoProject/pull/4#discussion_r697552410>
> :
>
> > +    public class PasswordService : IPasswordService
> +    {
> +        public string GenerateSHA256Hash(String password, String salt)
> +        {
> +            byte[] bytes = System.Text.Encoding.UTF8.GetBytes(password + salt);
> +            SHA256Managed sha256HashString = new SHA256Managed();
> +            byte[] hash = sha256HashString.ComputeHash(bytes);
> +
> +            return Convert.ToBase64String(hash);
> +        }
> +
> +        public string GenerateSalt(int size)
> +        {
> +            var bytes = new byte[size];
> +            var rng = new RNGCryptoServiceProvider();
> +            rng.GetBytes(bytes);
>
> This will fill variable *bytes* with random bytes. Therefore, your
> password hash will be changed when you trying to compare it with saved hash
> password. Or am I wrong?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/DeanHoang/.NET_Team_DemoProject/pull/4#pullrequestreview-740672746>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMLQQN3SRKJD2PMVB5YXZRDT66Y25ANCNFSM5CYVNXYQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-08-28 01:26 UTC, Trinhnguyen1704 commented on DEMO-PROJECT-BE/DP.Service/Implement/Auth/PasswordService.cs
> +            rng.GetBytes(bytes);
Hi, Cuong!
I researched and tested the hash and salt, I follow this way when we login:

Firstly, check whether the user name exists. If it exists, get the user's
salt.

Secondly, use the salt and the password which was entered by the user to
compute the hash value as passwordandsalt field.

Finally, compare the passwordandsalt with the hash value in the database.

So we need to add a salt field in Account entity.

Could you give me reviews for this solution ?

Thank you so much!

2021-08-28 03:14 UTC, Trinhnguyen1704 commented on DEMO-PROJECT-BE/DP.Service/Implement/Auth/PasswordService.cs
> +            rng.GetBytes(bytes);
![pass](https://user-images.githubusercontent.com/51841079/131204485-719c35c3-4ed7-40ec-85fb-6c2536c456bc.png)

![passfalse](https://user-images.githubusercontent.com/51841079/131204543-5eefb58d-8090-446c-b5f0-a9b71e34bef3.png)

I plan to do it like this when logging in, the salt is taken from the database which is saved when registering the account.

2021-08-28 03:14 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Service/Implement/Auth/PasswordService.cs
> +            rng.GetBytes(bytes);
You should put your salt key some where in config file. And use it for all user.

2021-08-28 03:17 UTC, Trinhnguyen1704 commented on DEMO-PROJECT-BE/DP.Service/Implement/Auth/PasswordService.cs
> +            rng.GetBytes(bytes);
Yes, I understand it, so I don't have to create a salt field for each account. We use a salt key for all user. I will fix it.

2021-08-28 03:19 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP.Service/Implement/Auth/PasswordService.cs
> +            rng.GetBytes(bytes);
Thank you

2021-08-28 06:08 UTC, vancuong196 commented on DEMO-PROJECT-BE/DP/Startup.cs
> +                return new PasswordService(saltKey);
I don't see this constructor in your PasswordService class?

2021-08-28 06:12 UTC, Trinhnguyen1704 commented on DEMO-PROJECT-BE/DP/Startup.cs
> +                return new PasswordService(saltKey);
Sorry, I forgot to commit it!

2021-08-28 06:40 UTC, merged